substitutions:
  _DESAFIO_CI_VERSION: 1.0.0
steps:
  - id: "Executando build e subindo imagem para GCR privado"
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/desafio-ci:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/desafio-ci:${_DESAFIO_CI_VERSION}'
      - '.'
      
  - id: "Rodando testes"
    name: "gcr.io/cloud-builders/go"
    args: ["test", "."]
    env: 
      - "GOPATH=."
    dir: "./src/soma"
    
  - id: "Executando a função soma"
    name: "gcr.io/cloud-builders/go"
    args: ["run", "."]
    env: ["GOPATH=."]
    dir: "./src/soma"

images:
  - 'gcr.io/$PROJECT_ID/desafio-ci:latest'
  - 'gcr.io/$PROJECT_ID/desafio-ci:${_DESAFIO_CI_VERSION}'
tags: ['fullcycle-desafio-ci']